baseurl = "https://contentcamel.io"
copyright = ""
defaultContentLanguage = "en"
destination = "../dist/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
metaDataFormat = "yaml"
paginate = 10
pluralizeListTitles = false
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"
relativeURLs = false
title = "Content Camel"  
[markup]
defaultMarkdownHandler = "blackfriday"
[blackfriday]
angledQuotes = false
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true
[[menu.footer]]
name = "Docs"
parent = "Product"
url = "https://learn.contentcamel.io/"
weight = 6
[[menu.footer]]
name = "Get started"
parent = "Product"
url = "https://app.contentcamel.io/signup"
weight = 7
[[menu.footer]]
name = "Company"
weight = 3
[[menu.footer]]
name = "Product"
weight = 2
[[menu.footer]]
name = "Sales Enablement"
weight = 1
[[menu.footer]]
name = "Highspot alternative"
parent = "Sales Enablement"
url = "https://www.contentcamel.io/highspot-competitors/"
weight = 2
[[menu.footer]]
name = "Seismic alternative"
parent = "Sales Enablement"
url = "https://www.contentcamel.io/alternatives/seismic-competitors/"
weight = 3
[[menu.footer]]
name = "Showpad alternative"
parent = "Sales Enablement"
url = "https://www.contentcamel.io/showpad-competitors/"
weight = 4
[[menu.footer]]
name = "Bigtincan alternative"
parent = "Sales Enablement"
url = "https://www.contentcamel.io/bigtincan-competitors/"
weight = 5
[[menu.footer]]
name = "How to do a sales content audit"
parent = "Sales Enablement"
url = "https://www.contentcamel.io/blog/how-to-do-a-sales-content-audit/"
weight = 6
[[menu.main]]
identifier = "useraccount"
name = "My Account"
url = "https://app.contentcamel.io/"
weight = 5
[[menu.main]]
identifier = "signup"
name = "Sign up"
url = "https://app.contentcamel.io/signup"
weight = 8
[[menu.main]]
identifier = "userdashboard"
name = "Dashboard"
url = "https://app.contentcamel.io/"
weight = 7
[[menu.main]]
identifier = "login"
name = "Login"
url = "https://app.contentcamel.io/login"
weight = 6
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputFormats.OpenSearch]
baseName = "opensearch"
isPlainText = true
mediaType = "application/xml"
notAlternative = true
[outputFormats.Redirects]
baseName = "redirects"
isPlainText = true
mediatype = "application/json"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "OpenSearch", "Algolia", "Redirects"]
[params]
dateformat = "January 2, 2006"
description = "Cost effective sales enablement tool that gives sales reps the right content at the right time to have better interactions and more wins. Get a Free Trial!"
gtmid = "GTM-PBQCVND"
images = ["/uploads/2018/01/OGimage-01-3x.jpg"]
[params.algolia]
params = ["tags", "categories", "authors"]
vars = ["date", "description", "dir", "path", "expirydate", "fuzzywordcount", "keywords", "kind", "lang", "lastmod", "permalink", "publishdate", "readingtime", "relpermalink", "summary", "title", "type", "url", "weight", "wordcount", "section"]
[params.cloudinary]
cloud_name = "contentcamel-io"
use_upload = false
baseurl = "https://res.cloudinary.com/contentcamel-io/image/fetch"
[params.cloudinary.lazysizes]
enabled = true
[params.cloudinary.presets.content]
max_width = 1920
min_width = 320
quality = 80
sizes = "auto"
steps = 10
width = 640
[params.cloudinary.presets.default]
quality = 80
[params.cloudinary.presets.feature]
max_width = 1920
min_width = 320
quality = 80
sizes = "(max-width: 76px) 100%, 800px"
steps = 10
width = 640
[related]
includeNewer = true
threshold = 10
toLower = true
[[related.indices]]
name = "Section"
weight = 200
[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "categories"
weight = 150
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
pattern = "2006"
weight = 10
[social]
email = "support@contentcamel.io"
newsletter = "/join-newsletter/"
twitter = ""
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
